feat: rule no-unsafe-values
eslint/json pull request #30
Opened 2024-10-03 16:47 UTC by bmeck

#### Prerequisites checklist

-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Introduce a new rule for checking common interchange problems

#### What changes did you make? (Give an overview)

Added a rule for:

- non-finite (Infinity, null, NaN) values.
- lone surrogates due to UTF16

#### Related Issues

fixes #29

#### Is there anything you'd like reviewers to focus on?

tests are somewhat limited by using already parsed values so I avoided trying to reparse for getting exact locations within strings and/or couldn't check array/string bounds since things error before getting to the rules processing phase.

2024-10-03 17:16 UTC, bmeck commented
Easy CLA is giving me a wildly inaccurate corporate account. Will have to work around sometime as I can't select a different corporation

2024-10-04 15:01 UTC, nzakas requested changes
This looks like a good start. Some high-level notes:

1. Please add this rule to the rules table on the README
2. Please add this rule to the recommended configuration

Also, it looks like your last invalid test is actually producing two errors instead of one. Can you double-check that?

2024-10-07 22:42 UTC, bmeck commented on src/rules/no-unsafe-values.js
> +							messageId: "loneSurrogate",
sure

2024-10-13 10:51 UTC, mdjermanovic commented on tests/rules/no-unsafe-values.test.js
> +				},
Can you add `data` to all test errors with `messageId: "loneSurrogate"`?

2024-10-18 15:57 UTC, nzakas commented
@bmeck just one outstanding comment to address here.

2024-11-07 21:14 UTC, nzakas approved these changes
Because we're just waiting for a change to the tests, I'll merge this and then update the tests myself.

2024-11-07 21:14 UTC, merged